services:
  bottec_bot:
    build: .
    container_name: bottec_bot
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: >
      uvicorn app.bottec_bot.main:app
      --host 0.0.0.0
      --port 8080
    volumes:
      - .:/app
    depends_on:
      - postgres

  
  postgres:
    image: postgres:15
    container_name: pg_bottec
    restart: always
    ports:
      - "5423:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: