services:
  bottec_bot:
    build: .
    container_name: bottec_bot
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: >
      uvicorn app.bottec_bot.main:app
      --host 0.0.0.0
      --port 8080
    volumes:
      - .:/app